# Generated by Django 5.2.9 on 2025-12-14 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the task', max_length=255)),
                ('description', models.TextField(blank=True, default='', help_text='Detailed description of the task')),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('done', 'Done')], default='todo', help_text='Current status of the task', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', help_text='Priority level of the task', max_length=20)),
                ('due_date', models.DateField(blank=True, help_text='Due date for the task', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the task was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When the task was last updated')),
                ('user', models.ForeignKey(help_text='The user who owns this task', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='app_task_user_id_b58bb0_idx'), models.Index(fields=['user', 'priority'], name='app_task_user_id_dcfe65_idx'), models.Index(fields=['user', 'due_date'], name='app_task_user_id_e98f52_idx'), models.Index(fields=['created_at'], name='app_task_created_975b98_idx')],
            },
        ),
    ]
